package com.ecommerce.order.entity;
public enum OrderStatus { CREATED, CONFIRMED, PENDING_PAYMENT, PAYMENT_PENDING_VERIFICATION, PAID, PROCESSING, SHIPPED, OUT_FOR_DELIVERY, DELIVERED, PAYMENT_FAILED, CANCELLED, FAILED }
