spring.application.name=cart-service
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
server.port=9094
spring.datasource.url=${CART_DB_URL:jdbc:mysql://localhost:3306/cart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.flyway.enabled=false
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
